# Generated by Django 3.1.2 on 2020-10-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201020_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='I love you'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='I love you'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(),
        ),
    ]
